export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_PANTRY = "GET_PANTRY";
export const DELETE_PANTRY = "DELETE_PANTRY";
export const ADD_PANTRY = "ADD_PANTRY";

export const GET_RECIPE = "GET_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const ADD_RECIPE = "ADD_RECIPE";

// spoonacular API
export const GENERATE_MEALPLAN = "GENERATE_MEALPLAN";
export const GENERATE_MEALPLAN_EXTENDED = "GENERATE_MEALPLAN_EXTENDED";

export const GET_RECIPE_RANDOM = "GET_RECIPE_RANDOM";
