export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_PANTRY = "GET_PANTRY";
export const DELETE_PANTRY = "DELETE_PANTRY";
export const ADD_PANTRY = "ADD_PANTRY";
export const UPDATE_PANTRY = "UPDATE_PANTRY";

export const GET_RECIPE = "GET_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE";
export const ADD_RECIPE = "ADD_RECIPE";

export const GET_SHOPPING_LIST = "GET_SHOPPING_LIST";
export const DELETE_SHOPPING_LIST = "DELETE_SHOPPING_LIST";
export const ADD_SHOPPING_LIST = "ADD_SHOPPING_LIST";
export const UPDATE_SHOPPING_LIST = "UPDATE_SHOPPING_LIST";

export const GET_MEALPLAN = "GET_MEALPLAN";
export const DELETE_MEALPLAN = "DELETE_MEALPLAN";
export const ADD_MEALPLAN = "ADD_MEALPLAN";
export const UPDATE_MEALPLAN = "UPDATE_MEALPLAN";

// spoonacular API
export const GENERATE_MEALPLAN = "GENERATE_MEALPLAN";
export const GENERATE_MEALPLAN_EXTENDED = "GENERATE_MEALPLAN_EXTENDED";

export const GET_RECIPE_RANDOM = "GET_RECIPE_RANDOM";
export const GET_RECIPE_BY_INGREDIENTS = "GET_RECIPE_BY_INGREDIENTS";
export const GET_RECIPE_BY_TYPE = "GET_RECIPE_BY_TYPE";
export const GET_RECIPE_INFO = "GET_RECIPE_INFO";
export const GET_RECIPE_INFO_BULK = "GET_RECIPE_INFO_BULK";
