# Generated by Django 3.0.5 on 2020-05-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='carbohydrates',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='fat',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='protein',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
