# Generated by Django 3.0.5 on 2020-05-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_pantry_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantry',
            name='ingredient_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
