# Generated by Django 3.0.5 on 2020-05-08 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='inMealplan',
            field=models.BooleanField(default=False),
        ),
    ]
